// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: steammessages_unified_base.steamclient.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "steammessages_unified_base.steamclient.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace steam {
class NoResponseDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<NoResponse> {
} _NoResponse_default_instance_;

namespace protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NoResponse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NoResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 5, sizeof(NoResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_NoResponse_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "steammessages_unified_base.steamclient.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _NoResponse_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::google::protobuf::protobuf_google_2fprotobuf_2fdescriptor_2eproto::InitDefaults();
  _NoResponse_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    ::google::protobuf::FieldOptions::internal_default_instance(),
    50000, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    ::google::protobuf::ServiceOptions::internal_default_instance(),
    50000, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterEnumExtension(
    ::google::protobuf::ServiceOptions::internal_default_instance(),
    50008, 14, false, false,
    &::proto::steam::EProtoExecutionSite_IsValid);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    ::google::protobuf::MethodOptions::internal_default_instance(),
    50000, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    ::google::protobuf::EnumOptions::internal_default_instance(),
    50000, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    ::google::protobuf::EnumValueOptions::internal_default_instance(),
    50000, 9, false, false);
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n,steammessages_unified_base.steamclient"
      ".proto\022\013proto.steam\032 google/protobuf/des"
      "criptor.proto\"\014\n\nNoResponse*]\n\023EProtoExe"
      "cutionSite\022 \n\034k_EProtoExecutionSiteUnkno"
      "wn\020\000\022$\n k_EProtoExecutionSiteSteamClient"
      "\020\002:4\n\013description\022\035.google.protobuf.Fiel"
      "dOptions\030\320\206\003 \001(\t:>\n\023service_description\022"
      "\037.google.protobuf.ServiceOptions\030\320\206\003 \001(\t"
      ":\201\001\n\026service_execution_site\022\037.google.pro"
      "tobuf.ServiceOptions\030\330\206\003 \001(\0162 .proto.ste"
      "am.EProtoExecutionSite:\034k_EProtoExecutio"
      "nSiteUnknown:<\n\022method_description\022\036.goo"
      "gle.protobuf.MethodOptions\030\320\206\003 \001(\t:8\n\020en"
      "um_description\022\034.google.protobuf.EnumOpt"
      "ions\030\320\206\003 \001(\t:C\n\026enum_value_description\022!"
      ".google.protobuf.EnumValueOptions\030\320\206\003 \001("
      "\tB\005H\001\200\001\000"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 648);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "steammessages_unified_base.steamclient.proto", &protobuf_RegisterTypes);
  ::google::protobuf::protobuf_google_2fprotobuf_2fdescriptor_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto

const ::google::protobuf::EnumDescriptor* EProtoExecutionSite_descriptor() {
  protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto::file_level_enum_descriptors[0];
}
bool EProtoExecutionSite_IsValid(int value) {
  switch (value) {
    case 0:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NoResponse::NoResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.steam.NoResponse)
}
NoResponse::NoResponse(const NoResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:proto.steam.NoResponse)
}

void NoResponse::SharedCtor() {
  _cached_size_ = 0;
}

NoResponse::~NoResponse() {
  // @@protoc_insertion_point(destructor:proto.steam.NoResponse)
  SharedDtor();
}

void NoResponse::SharedDtor() {
}

void NoResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NoResponse::descriptor() {
  protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NoResponse& NoResponse::default_instance() {
  protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto::InitDefaults();
  return *internal_default_instance();
}

NoResponse* NoResponse::New(::google::protobuf::Arena* arena) const {
  NoResponse* n = new NoResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void NoResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.steam.NoResponse)
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool NoResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.steam.NoResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:proto.steam.NoResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.steam.NoResponse)
  return false;
#undef DO_
}

void NoResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.steam.NoResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.steam.NoResponse)
}

::google::protobuf::uint8* NoResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.steam.NoResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.steam.NoResponse)
  return target;
}

size_t NoResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.steam.NoResponse)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NoResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.steam.NoResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const NoResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NoResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.steam.NoResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.steam.NoResponse)
    MergeFrom(*source);
  }
}

void NoResponse::MergeFrom(const NoResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.steam.NoResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void NoResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.steam.NoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NoResponse::CopyFrom(const NoResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.steam.NoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NoResponse::IsInitialized() const {
  return true;
}

void NoResponse::Swap(NoResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NoResponse::InternalSwap(NoResponse* other) {
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata NoResponse::GetMetadata() const {
  protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// NoResponse

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS
const ::std::string description_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  description(kDescriptionFieldNumber, description_default);
const ::std::string service_description_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  service_description(kServiceDescriptionFieldNumber, service_description_default);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::proto::steam::EProtoExecutionSite, ::proto::steam::EProtoExecutionSite_IsValid>, 14, false >
  service_execution_site(kServiceExecutionSiteFieldNumber, static_cast< ::proto::steam::EProtoExecutionSite >(0));
const ::std::string method_description_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  method_description(kMethodDescriptionFieldNumber, method_description_default);
const ::std::string enum_description_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  enum_description(kEnumDescriptionFieldNumber, enum_description_default);
const ::std::string enum_value_description_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  enum_value_description(kEnumValueDescriptionFieldNumber, enum_value_description_default);

// @@protoc_insertion_point(namespace_scope)

}  // namespace steam
}  // namespace proto

// @@protoc_insertion_point(global_scope)
