// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network_connection.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "network_connection.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace dota {

namespace protobuf_network_5fconnection_2eproto {


namespace {

const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = { ~0u };
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;
namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "network_connection.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      NULL, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void TableStruct::Shutdown() {
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::google::protobuf::protobuf_google_2fprotobuf_2fdescriptor_2eproto::InitDefaults();
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    ::google::protobuf::EnumValueOptions::internal_default_instance(),
    50500, 9, false, false);
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\030network_connection.proto\022\nproto.dota\032 "
      "google/protobuf/descriptor.proto*\234C\n\033ENe"
      "tworkDisconnectionReason\022\036\n\032NETWORK_DISC"
      "ONNECT_INVALID\020\000\022\037\n\033NETWORK_DISCONNECT_S"
      "HUTDOWN\020\001\022F\n%NETWORK_DISCONNECT_DISCONNE"
      "CT_BY_USER\020\002\032\033\242\324\030\027#GameUI_Disconnect_Use"
      "r\022J\n\'NETWORK_DISCONNECT_DISCONNECT_BY_SE"
      "RVER\020\003\032\035\242\324\030\031#GameUI_Disconnect_Server\022B\n"
      "\027NETWORK_DISCONNECT_LOST\020\004\032%\242\324\030!#GameUI_"
      "Disconnect_ConnectionLost\022J\n\033NETWORK_DIS"
      "CONNECT_OVERFLOW\020\005\032)\242\324\030%#GameUI_Disconne"
      "ct_ConnectionOverflow\022I\n\037NETWORK_DISCONN"
      "ECT_STEAM_BANNED\020\006\032$\242\324\030 #GameUI_Disconne"
      "ct_SteamIDBanned\022G\n\036NETWORK_DISCONNECT_S"
      "TEAM_INUSE\020\007\032#\242\324\030\037#GameUI_Disconnect_Ste"
      "amIDInUse\022G\n\037NETWORK_DISCONNECT_STEAM_TI"
      "CKET\020\010\032\"\242\324\030\036#GameUI_Disconnect_SteamTick"
      "et\022E\n\036NETWORK_DISCONNECT_STEAM_LOGON\020\t\032!"
      "\242\324\030\035#GameUI_Disconnect_SteamLogon\022M\n&NET"
      "WORK_DISCONNECT_STEAM_AUTHCANCELLED\020\n\032!\242"
      "\324\030\035#GameUI_Disconnect_SteamLogon\022O\n(NETW"
      "ORK_DISCONNECT_STEAM_AUTHALREADYUSED\020\013\032!"
      "\242\324\030\035#GameUI_Disconnect_SteamLogon\022K\n$NET"
      "WORK_DISCONNECT_STEAM_AUTHINVALID\020\014\032!\242\324\030"
      "\035#GameUI_Disconnect_SteamLogon\022I\n$NETWOR"
      "K_DISCONNECT_STEAM_VACBANSTATE\020\r\032\037\242\324\030\033#G"
      "ameUI_Disconnect_SteamVAC\022S\n,NETWORK_DIS"
      "CONNECT_STEAM_LOGGED_IN_ELSEWHERE\020\016\032!\242\324\030"
      "\035#GameUI_Disconnect_SteamInUse\022T\n+NETWOR"
      "K_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT\020\017\032"
      "#\242\324\030\037#GameUI_Disconnect_SteamTimeOut\022I\n "
      "NETWORK_DISCONNECT_STEAM_DROPPED\020\020\032#\242\324\030\037"
      "#GameUI_Disconnect_SteamDropped\022M\n\"NETWO"
      "RK_DISCONNECT_STEAM_OWNERSHIP\020\021\032%\242\324\030!#Ga"
      "meUI_Disconnect_SteamOwnership\022U\n&NETWOR"
      "K_DISCONNECT_SERVERINFO_OVERFLOW\020\022\032)\242\324\030%"
      "#GameUI_Disconnect_ServerInfoOverflow\022K\n"
      "#NETWORK_DISCONNECT_TICKMSG_OVERFLOW\020\023\032\""
      "\242\324\030\036#GameUI_Disconnect_TickMessage\022Y\n*NE"
      "TWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW"
      "\020\024\032)\242\324\030%#GameUI_Disconnect_StringTableMe"
      "ssage\022S\n\'NETWORK_DISCONNECT_DELTAENTMSG_"
      "OVERFLOW\020\025\032&\242\324\030\"#GameUI_Disconnect_Delta"
      "EntMessage\022Q\n&NETWORK_DISCONNECT_TEMPENT"
      "MSG_OVERFLOW\020\026\032%\242\324\030!#GameUI_Disconnect_T"
      "empEntMessage\022O\n%NETWORK_DISCONNECT_SOUN"
      "DSMSG_OVERFLOW\020\027\032$\242\324\030 #GameUI_Disconnect"
      "_SoundsMessage\022P\n#NETWORK_DISCONNECT_SNA"
      "PSHOTOVERFLOW\020\030\032\'\242\324\030##GameUI_Disconnect_"
      "SnapshotOverflow\022J\n NETWORK_DISCONNECT_S"
      "NAPSHOTERROR\020\031\032$\242\324\030 #GameUI_Disconnect_S"
      "napshotError\022P\n#NETWORK_DISCONNECT_RELIA"
      "BLEOVERFLOW\020\032\032\'\242\324\030##GameUI_Disconnect_Re"
      "liableOverflow\022N\n\037NETWORK_DISCONNECT_BAD"
      "DELTATICK\020\033\032)\242\324\030%#GameUI_Disconnect_BadC"
      "lientDeltaTick\022H\n\037NETWORK_DISCONNECT_NOM"
      "ORESPLITS\020\034\032#\242\324\030\037#GameUI_Disconnect_NoMo"
      "reSplits\022@\n\033NETWORK_DISCONNECT_TIMEDOUT\020"
      "\035\032\037\242\324\030\033#GameUI_Disconnect_TimedOut\022H\n\037NE"
      "TWORK_DISCONNECT_DISCONNECTED\020\036\032#\242\324\030\037#Ga"
      "meUI_Disconnect_Disconnected\022H\n\037NETWORK_"
      "DISCONNECT_LEAVINGSPLIT\020\037\032#\242\324\030\037#GameUI_D"
      "isconnect_LeavingSplit\022X\n\'NETWORK_DISCON"
      "NECT_DIFFERENTCLASSTABLES\020 \032+\242\324\030\'#GameUI"
      "_Disconnect_DifferentClassTables\022P\n#NETW"
      "ORK_DISCONNECT_BADRELAYPASSWORD\020!\032\'\242\324\030##"
      "GameUI_Disconnect_BadRelayPassword\022X\n\'NE"
      "TWORK_DISCONNECT_BADSPECTATORPASSWORD\020\"\032"
      "+\242\324\030\'#GameUI_Disconnect_BadSpectatorPass"
      "word\022L\n!NETWORK_DISCONNECT_HLTVRESTRICTE"
      "D\020#\032%\242\324\030!#GameUI_Disconnect_HLTVRestrict"
      "ed\022H\n\037NETWORK_DISCONNECT_NOSPECTATORS\020$\032"
      "#\242\324\030\037#GameUI_Disconnect_NoSpectators\022N\n\""
      "NETWORK_DISCONNECT_HLTVUNAVAILABLE\020%\032&\242\324"
      "\030\"#GameUI_Disconnect_HLTVUnavailable\022@\n\033"
      "NETWORK_DISCONNECT_HLTVSTOP\020&\032\037\242\324\030\033#Game"
      "UI_Disconnect_HLTVStop\022<\n\031NETWORK_DISCON"
      "NECT_KICKED\020\'\032\035\242\324\030\031#GameUI_Disconnect_Ki"
      "cked\022@\n\033NETWORK_DISCONNECT_BANADDED\020(\032\037\242"
      "\324\030\033#GameUI_Disconnect_BanAdded\022H\n\037NETWOR"
      "K_DISCONNECT_KICKBANADDED\020)\032#\242\324\030\037#GameUI"
      "_Disconnect_KickBanAdded\022D\n\035NETWORK_DISC"
      "ONNECT_HLTVDIRECT\020*\032!\242\324\030\035#GameUI_Disconn"
      "ect_HLTVDirect\022\\\n)NETWORK_DISCONNECT_PUR"
      "ESERVER_CLIENTEXTRA\020+\032-\242\324\030)#GameUI_Disco"
      "nnect_PureServer_ClientExtra\022V\n&NETWORK_"
      "DISCONNECT_PURESERVER_MISMATCH\020,\032*\242\324\030&#G"
      "ameUI_Disconnect_PureServer_Mismatch\022>\n\032"
      "NETWORK_DISCONNECT_USERCMD\020-\032\036\242\324\030\032#GameU"
      "I_Disconnect_UserCmd\022N\n#NETWORK_DISCONNE"
      "CT_REJECTED_BY_GAME\020.\032%\242\324\030!#GameUI_Disco"
      "nnect_RejectedByGame\022T\n&NETWORK_DISCONNE"
      "CT_MESSAGE_PARSE_ERROR\020/\032(\242\324\030$#GameUI_Di"
      "sconnect_MessageParseError\022X\n(NETWORK_DI"
      "SCONNECT_INVALID_MESSAGE_ERROR\0200\032*\242\324\030&#G"
      "ameUI_Disconnect_InvalidMessageError\022T\n&"
      "NETWORK_DISCONNECT_BAD_SERVER_PASSWORD\0201"
      "\032(\242\324\030$#GameUI_Disconnect_BadServerPasswo"
      "rd\0221\n-NETWORK_DISCONNECT_DIRECT_CONNECT_"
      "RESERVATION\0202\022S\n%NETWORK_DISCONNECT_CONN"
      "ECTION_FAILURE\0203\032(\242\324\030$#GameUI_Disconnect"
      "_ConnectionFailure\022Y\n)NETWORK_DISCONNECT"
      "_NO_PEER_GROUP_HANDLERS\0204\032*\242\324\030&#GameUI_D"
      "isconnect_NoPeerGroupHandlers\022#\n\037NETWORK"
      "_DISCONNECT_RECONNECTION\0205\022H\n\037NETWORK_DI"
      "SCONNECT_LOOPSHUTDOWN\0206\032#\242\324\030\037#GameUI_Dis"
      "connect_LoopShutdown\022L\n!NETWORK_DISCONNE"
      "CT_LOOPDEACTIVATE\0207\032%\242\324\030!#GameUI_Disconn"
      "ect_LoopDeactivate\022H\n\037NETWORK_DISCONNECT"
      "_HOST_ENDGAME\0208\032#\242\324\030\037#GameUI_Disconnect_"
      "Host_EndGame\022\\\n*NETWORK_DISCONNECT_LOOP_"
      "LEVELLOAD_ACTIVATE\0209\032,\242\324\030(#GameUI_Discon"
      "nect_LoopLevelLoadActivate\022V\n\'NETWORK_DI"
      "SCONNECT_CREATE_SERVER_FAILED\020:\032)\242\324\030%#Ga"
      "meUI_Disconnect_CreateServerFailed\022D\n\032NE"
      "TWORK_DISCONNECT_EXITING\020;\032$\242\324\030 #GameUI_"
      "Disconnect_ExitingEngine\022T\n)NETWORK_DISC"
      "ONNECT_REQUEST_HOSTSTATE_IDLE\020<\032%\242\324\030!#Ga"
      "meUI_Disconnect_Request_HSIdle\022\\\n.NETWOR"
      "K_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY"
      "\020=\032(\242\324\030$#GameUI_Disconnect_Request_HLTVR"
      "elay\022Q\n*NETWORK_DISCONNECT_CLIENT_CONSIS"
      "TENCY_FAIL\020>\032!\242\324\030\035#GameUI_ClientConsiste"
      "ncyFail\022Q\n+NETWORK_DISCONNECT_CLIENT_UNA"
      "BLE_TO_CRC_MAP\020\?\032 \242\324\030\034#GameUI_ClientUnab"
      "leToCRCMap\022=\n NETWORK_DISCONNECT_CLIENT_"
      "NO_MAP\020@\032\027\242\324\030\023#GameUI_ClientNoMap\022K\n\'NET"
      "WORK_DISCONNECT_CLIENT_DIFFERENT_MAP\020A\032\036"
      "\242\324\030\032#GameUI_ClientDifferentMap\022M\n(NETWOR"
      "K_DISCONNECT_SERVER_REQUIRES_STEAM\020B\032\037\242\324"
      "\030\033#GameUI_ServerRequireSteams\022M\n\"NETWORK"
      "_DISCONNECT_STEAM_DENY_MISC\020C\032%\242\324\030!#Game"
      "UI_Disconnect_SteamDeny_Misc\022_\n,NETWORK_"
      "DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT\020D\032-"
      "\242\324\030)#GameUI_Disconnect_SteamDeny_BadAnti"
      "Cheat\022M\n\"NETWORK_DISCONNECT_SERVER_SHUTD"
      "OWN\020E\032%\242\324\030!#GameUI_Disconnect_ServerShut"
      "down\022b\n,NETWORK_DISCONNECT_SPLITPACKET_S"
      "END_OVERFLOW\020F\0320\242\324\030,#GameUI_Disconnect_S"
      "plitpacket_Send_Overflow\022U\n&NETWORK_DISC"
      "ONNECT_REPLAY_INCOMPATIBLE\020G\032)\242\324\030%#GameU"
      "I_Disconnect_ReplayIncompatible\022Z\n+NETWO"
      "RK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT\020H"
      "\032)\242\324\030%#GameUI_Disconnect_ConnectionTimed"
      "out\022U\n&NETWORK_DISCONNECT_SERVER_INCOMPA"
      "TIBLE\020I\032)\242\324\030%#GameUI_Disconnect_ServerIn"
      "compatible\022^\n*NETWORK_DISCONNECT_LOCALPR"
      "OBLEM_MANYRELAYS\020J\032.\242\324\030*#GameUI_Disconne"
      "ct_LocalProblem_ManyRelays\022z\n8NETWORK_DI"
      "SCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMAR"
      "YRELAY\020K\032<\242\324\0308#GameUI_Disconnect_LocalPr"
      "oblem_HostedServerPrimaryRelay\022d\n-NETWOR"
      "K_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG\020"
      "L\0321\242\324\030-#GameUI_Disconnect_LocalProblem_N"
      "etworkConfig\022T\n%NETWORK_DISCONNECT_LOCAL"
      "PROBLEM_OTHER\020M\032)\242\324\030%#GameUI_Disconnect_"
      "LocalProblem_Other\022S\n!NETWORK_DISCONNECT"
      "_REMOTE_TIMEOUT\020O\032,\242\324\030(#GameUI_Disconnec"
      "t_RemoteProblem_Timeout\022h\n,NETWORK_DISCO"
      "NNECT_REMOTE_TIMEOUT_CONNECTING\020P\0326\242\324\0302#"
      "GameUI_Disconnect_RemoteProblem_TimeoutC"
      "onnecting\022O\n\037NETWORK_DISCONNECT_REMOTE_O"
      "THER\020Q\032*\242\324\030&#GameUI_Disconnect_RemotePro"
      "blem_Other\022U\n\"NETWORK_DISCONNECT_REMOTE_"
      "BADCRYPT\020R\032-\242\324\030)#GameUI_Disconnect_Remot"
      "eProblem_BadCrypt\022Z\n(NETWORK_DISCONNECT_"
      "REMOTE_CERTNOTTRUSTED\020S\032,\242\324\030(#GameUI_Dis"
      "connect_RemoteProblem_BadCert\022>\n\032NETWORK"
      "_DISCONNECT_UNUSUAL\020T\032\036\242\324\030\032#GameUI_Disco"
      "nnect_Unusual\022K\n!NETWORK_DISCONNECT_INTE"
      "RNAL_ERROR\020U\032$\242\324\030 #GameUI_Disconnect_Int"
      "ernalError\022Q\n&NETWORK_DISCONNECT_REJECT_"
      "BADCHALLENGE\020\200\001\032$\242\324\030 #GameUI_ServerRejec"
      "tBadChallenge\022A\n!NETWORK_DISCONNECT_REJE"
      "CT_NOLOBBY\020\201\001\032\031\242\324\030\025#GameUI_ServerNoLobby"
      "\022O\n(NETWORK_DISCONNECT_REJECT_BACKGROUND"
      "_MAP\020\202\001\032 \242\324\030\034#Valve_Reject_Background_Ma"
      "p\022M\n\'NETWORK_DISCONNECT_REJECT_SINGLE_PL"
      "AYER\020\203\001\032\037\242\324\030\033#Valve_Reject_Single_Player"
      "\022I\n%NETWORK_DISCONNECT_REJECT_HIDDEN_GAM"
      "E\020\204\001\032\035\242\324\030\031#Valve_Reject_Hidden_Game\022O\n%N"
      "ETWORK_DISCONNECT_REJECT_LANRESTRICT\020\205\001\032"
      "#\242\324\030\037#GameUI_ServerRejectLANRestrict\022O\n%"
      "NETWORK_DISCONNECT_REJECT_BADPASSWORD\020\206\001"
      "\032#\242\324\030\037#GameUI_ServerRejectBadPassword\022M\n"
      "$NETWORK_DISCONNECT_REJECT_SERVERFULL\020\207\001"
      "\032\"\242\324\030\036#GameUI_ServerRejectServerFull\022]\n,"
      "NETWORK_DISCONNECT_REJECT_INVALIDRESERVA"
      "TION\020\210\001\032*\242\324\030&#GameUI_ServerRejectInvalid"
      "Reservation\022S\n\'NETWORK_DISCONNECT_REJECT"
      "_FAILEDCHANNEL\020\211\001\032%\242\324\030!#GameUI_ServerRej"
      "ectFailedChannel\022W\n,NETWORK_DISCONNECT_R"
      "EJECT_CONNECT_FROM_LOBBY\020\212\001\032$\242\324\030 #Valve_"
      "Reject_Connect_From_Lobby\022W\n,NETWORK_DIS"
      "CONNECT_REJECT_RESERVED_FOR_LOBBY\020\213\001\032$\242\324"
      "\030 #Valve_Reject_Reserved_For_Lobby\022Z\n*NE"
      "TWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH"
      "\020\214\001\032)\242\324\030%#GameUI_ServerReject_InvalidKey"
      "Length\022O\n%NETWORK_DISCONNECT_REJECT_OLDP"
      "ROTOCOL\020\215\001\032#\242\324\030\037#GameUI_ServerRejectOldP"
      "rotocol\022O\n%NETWORK_DISCONNECT_REJECT_NEW"
      "PROTOCOL\020\216\001\032#\242\324\030\037#GameUI_ServerRejectNew"
      "Protocol\022[\n+NETWORK_DISCONNECT_REJECT_IN"
      "VALIDCONNECTION\020\217\001\032)\242\324\030%#GameUI_ServerRe"
      "jectInvalidConnection\022U\n(NETWORK_DISCONN"
      "ECT_REJECT_INVALIDCERTLEN\020\220\001\032&\242\324\030\"#GameU"
      "I_ServerRejectInvalidCertLen\022_\n-NETWORK_"
      "DISCONNECT_REJECT_INVALIDSTEAMCERTLEN\020\221\001"
      "\032+\242\324\030\'#GameUI_ServerRejectInvalidSteamCe"
      "rtLen\022C\n\037NETWORK_DISCONNECT_REJECT_STEAM"
      "\020\222\001\032\035\242\324\030\031#GameUI_ServerRejectSteam\022Q\n,NE"
      "TWORK_DISCONNECT_REJECT_SERVERAUTHDISABL"
      "ED\020\223\001\032\036\242\324\030\032#GameUI_ServerAuthDisabled\022Y\n"
      "0NETWORK_DISCONNECT_REJECT_SERVERCDKEYAU"
      "THINVALID\020\224\001\032\"\242\324\030\036#GameUI_ServerCDKeyAut"
      "hInvalid\022E\n NETWORK_DISCONNECT_REJECT_BA"
      "NNED\020\225\001\032\036\242\324\030\032#GameUI_ServerRejectBanned:"
      "E\n\030network_connection_token\022!.google.pro"
      "tobuf.EnumValueOptions\030\304\212\003 \001(\tB\003\200\001\000"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 8755);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "network_connection.proto", &protobuf_RegisterTypes);
  ::google::protobuf::protobuf_google_2fprotobuf_2fdescriptor_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_network_5fconnection_2eproto

const ::google::protobuf::EnumDescriptor* ENetworkDisconnectionReason_descriptor() {
  protobuf_network_5fconnection_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_network_5fconnection_2eproto::file_level_enum_descriptors[0];
}
bool ENetworkDisconnectionReason_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
    case 32:
    case 33:
    case 34:
    case 35:
    case 36:
    case 37:
    case 38:
    case 39:
    case 40:
    case 41:
    case 42:
    case 43:
    case 44:
    case 45:
    case 46:
    case 47:
    case 48:
    case 49:
    case 50:
    case 51:
    case 52:
    case 53:
    case 54:
    case 55:
    case 56:
    case 57:
    case 58:
    case 59:
    case 60:
    case 61:
    case 62:
    case 63:
    case 64:
    case 65:
    case 66:
    case 67:
    case 68:
    case 69:
    case 70:
    case 71:
    case 72:
    case 73:
    case 74:
    case 75:
    case 76:
    case 77:
    case 79:
    case 80:
    case 81:
    case 82:
    case 83:
    case 84:
    case 85:
    case 128:
    case 129:
    case 130:
    case 131:
    case 132:
    case 133:
    case 134:
    case 135:
    case 136:
    case 137:
    case 138:
    case 139:
    case 140:
    case 141:
    case 142:
    case 143:
    case 144:
    case 145:
    case 146:
    case 147:
    case 148:
    case 149:
      return true;
    default:
      return false;
  }
}

const ::std::string network_connection_token_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  network_connection_token(kNetworkConnectionTokenFieldNumber, network_connection_token_default);

// @@protoc_insertion_point(namespace_scope)

}  // namespace dota
}  // namespace proto

// @@protoc_insertion_point(global_scope)
