// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: steammessages_oauth.steamworkssdk.proto

#ifndef PROTOBUF_INCLUDED_steammessages_5foauth_2esteamworkssdk_2eproto
#define PROTOBUF_INCLUDED_steammessages_5foauth_2esteamworkssdk_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "steammessages_unified_base.steamworkssdk.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_steammessages_5foauth_2esteamworkssdk_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_steammessages_5foauth_2esteamworkssdk_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_steammessages_5foauth_2esteamworkssdk_2eproto();
namespace proto {
namespace dota {
class COAuthToken_ImplicitGrantNoPrompt_Request;
class COAuthToken_ImplicitGrantNoPrompt_RequestDefaultTypeInternal;
extern COAuthToken_ImplicitGrantNoPrompt_RequestDefaultTypeInternal _COAuthToken_ImplicitGrantNoPrompt_Request_default_instance_;
class COAuthToken_ImplicitGrantNoPrompt_Response;
class COAuthToken_ImplicitGrantNoPrompt_ResponseDefaultTypeInternal;
extern COAuthToken_ImplicitGrantNoPrompt_ResponseDefaultTypeInternal _COAuthToken_ImplicitGrantNoPrompt_Response_default_instance_;
}  // namespace dota
}  // namespace proto
namespace google {
namespace protobuf {
template<> ::proto::dota::COAuthToken_ImplicitGrantNoPrompt_Request* Arena::CreateMaybeMessage<::proto::dota::COAuthToken_ImplicitGrantNoPrompt_Request>(Arena*);
template<> ::proto::dota::COAuthToken_ImplicitGrantNoPrompt_Response* Arena::CreateMaybeMessage<::proto::dota::COAuthToken_ImplicitGrantNoPrompt_Response>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace proto {
namespace dota {

// ===================================================================

class COAuthToken_ImplicitGrantNoPrompt_Request final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Request) */ {
 public:
  COAuthToken_ImplicitGrantNoPrompt_Request();
  virtual ~COAuthToken_ImplicitGrantNoPrompt_Request();

  COAuthToken_ImplicitGrantNoPrompt_Request(const COAuthToken_ImplicitGrantNoPrompt_Request& from);

  inline COAuthToken_ImplicitGrantNoPrompt_Request& operator=(const COAuthToken_ImplicitGrantNoPrompt_Request& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  COAuthToken_ImplicitGrantNoPrompt_Request(COAuthToken_ImplicitGrantNoPrompt_Request&& from) noexcept
    : COAuthToken_ImplicitGrantNoPrompt_Request() {
    *this = ::std::move(from);
  }

  inline COAuthToken_ImplicitGrantNoPrompt_Request& operator=(COAuthToken_ImplicitGrantNoPrompt_Request&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const COAuthToken_ImplicitGrantNoPrompt_Request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const COAuthToken_ImplicitGrantNoPrompt_Request* internal_default_instance() {
    return reinterpret_cast<const COAuthToken_ImplicitGrantNoPrompt_Request*>(
               &_COAuthToken_ImplicitGrantNoPrompt_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(COAuthToken_ImplicitGrantNoPrompt_Request* other);
  friend void swap(COAuthToken_ImplicitGrantNoPrompt_Request& a, COAuthToken_ImplicitGrantNoPrompt_Request& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline COAuthToken_ImplicitGrantNoPrompt_Request* New() const final {
    return CreateMaybeMessage<COAuthToken_ImplicitGrantNoPrompt_Request>(nullptr);
  }

  COAuthToken_ImplicitGrantNoPrompt_Request* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<COAuthToken_ImplicitGrantNoPrompt_Request>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const COAuthToken_ImplicitGrantNoPrompt_Request& from);
  void MergeFrom(const COAuthToken_ImplicitGrantNoPrompt_Request& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(COAuthToken_ImplicitGrantNoPrompt_Request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string clientid = 1 [(.proto.dota.description) = "Client ID for which to count the number of issued tokens"];
  bool has_clientid() const;
  void clear_clientid();
  static const int kClientidFieldNumber = 1;
  const ::std::string& clientid() const;
  void set_clientid(const ::std::string& value);
  #if LANG_CXX11
  void set_clientid(::std::string&& value);
  #endif
  void set_clientid(const char* value);
  void set_clientid(const char* value, size_t size);
  ::std::string* mutable_clientid();
  ::std::string* release_clientid();
  void set_allocated_clientid(::std::string* clientid);

  // @@protoc_insertion_point(class_scope:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Request)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr clientid_;
  friend struct ::TableStruct_steammessages_5foauth_2esteamworkssdk_2eproto;
};
// -------------------------------------------------------------------

class COAuthToken_ImplicitGrantNoPrompt_Response final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Response) */ {
 public:
  COAuthToken_ImplicitGrantNoPrompt_Response();
  virtual ~COAuthToken_ImplicitGrantNoPrompt_Response();

  COAuthToken_ImplicitGrantNoPrompt_Response(const COAuthToken_ImplicitGrantNoPrompt_Response& from);

  inline COAuthToken_ImplicitGrantNoPrompt_Response& operator=(const COAuthToken_ImplicitGrantNoPrompt_Response& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  COAuthToken_ImplicitGrantNoPrompt_Response(COAuthToken_ImplicitGrantNoPrompt_Response&& from) noexcept
    : COAuthToken_ImplicitGrantNoPrompt_Response() {
    *this = ::std::move(from);
  }

  inline COAuthToken_ImplicitGrantNoPrompt_Response& operator=(COAuthToken_ImplicitGrantNoPrompt_Response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const COAuthToken_ImplicitGrantNoPrompt_Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const COAuthToken_ImplicitGrantNoPrompt_Response* internal_default_instance() {
    return reinterpret_cast<const COAuthToken_ImplicitGrantNoPrompt_Response*>(
               &_COAuthToken_ImplicitGrantNoPrompt_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(COAuthToken_ImplicitGrantNoPrompt_Response* other);
  friend void swap(COAuthToken_ImplicitGrantNoPrompt_Response& a, COAuthToken_ImplicitGrantNoPrompt_Response& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline COAuthToken_ImplicitGrantNoPrompt_Response* New() const final {
    return CreateMaybeMessage<COAuthToken_ImplicitGrantNoPrompt_Response>(nullptr);
  }

  COAuthToken_ImplicitGrantNoPrompt_Response* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<COAuthToken_ImplicitGrantNoPrompt_Response>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const COAuthToken_ImplicitGrantNoPrompt_Response& from);
  void MergeFrom(const COAuthToken_ImplicitGrantNoPrompt_Response& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(COAuthToken_ImplicitGrantNoPrompt_Response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string access_token = 1 [(.proto.dota.description) = "OAuth Token, granted on success"];
  bool has_access_token() const;
  void clear_access_token();
  static const int kAccessTokenFieldNumber = 1;
  const ::std::string& access_token() const;
  void set_access_token(const ::std::string& value);
  #if LANG_CXX11
  void set_access_token(::std::string&& value);
  #endif
  void set_access_token(const char* value);
  void set_access_token(const char* value, size_t size);
  ::std::string* mutable_access_token();
  ::std::string* release_access_token();
  void set_allocated_access_token(::std::string* access_token);

  // optional string redirect_uri = 2 [(.proto.dota.description) = "Redirection URI provided during client registration."];
  bool has_redirect_uri() const;
  void clear_redirect_uri();
  static const int kRedirectUriFieldNumber = 2;
  const ::std::string& redirect_uri() const;
  void set_redirect_uri(const ::std::string& value);
  #if LANG_CXX11
  void set_redirect_uri(::std::string&& value);
  #endif
  void set_redirect_uri(const char* value);
  void set_redirect_uri(const char* value, size_t size);
  ::std::string* mutable_redirect_uri();
  ::std::string* release_redirect_uri();
  void set_allocated_redirect_uri(::std::string* redirect_uri);

  // @@protoc_insertion_point(class_scope:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Response)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr access_token_;
  ::google::protobuf::internal::ArenaStringPtr redirect_uri_;
  friend struct ::TableStruct_steammessages_5foauth_2esteamworkssdk_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// COAuthToken_ImplicitGrantNoPrompt_Request

// optional string clientid = 1 [(.proto.dota.description) = "Client ID for which to count the number of issued tokens"];
inline bool COAuthToken_ImplicitGrantNoPrompt_Request::has_clientid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void COAuthToken_ImplicitGrantNoPrompt_Request::clear_clientid() {
  clientid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& COAuthToken_ImplicitGrantNoPrompt_Request::clientid() const {
  // @@protoc_insertion_point(field_get:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Request.clientid)
  return clientid_.GetNoArena();
}
inline void COAuthToken_ImplicitGrantNoPrompt_Request::set_clientid(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  clientid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Request.clientid)
}
#if LANG_CXX11
inline void COAuthToken_ImplicitGrantNoPrompt_Request::set_clientid(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  clientid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Request.clientid)
}
#endif
inline void COAuthToken_ImplicitGrantNoPrompt_Request::set_clientid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  clientid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Request.clientid)
}
inline void COAuthToken_ImplicitGrantNoPrompt_Request::set_clientid(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  clientid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Request.clientid)
}
inline ::std::string* COAuthToken_ImplicitGrantNoPrompt_Request::mutable_clientid() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Request.clientid)
  return clientid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* COAuthToken_ImplicitGrantNoPrompt_Request::release_clientid() {
  // @@protoc_insertion_point(field_release:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Request.clientid)
  if (!has_clientid()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return clientid_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void COAuthToken_ImplicitGrantNoPrompt_Request::set_allocated_clientid(::std::string* clientid) {
  if (clientid != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  clientid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), clientid);
  // @@protoc_insertion_point(field_set_allocated:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Request.clientid)
}

// -------------------------------------------------------------------

// COAuthToken_ImplicitGrantNoPrompt_Response

// optional string access_token = 1 [(.proto.dota.description) = "OAuth Token, granted on success"];
inline bool COAuthToken_ImplicitGrantNoPrompt_Response::has_access_token() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void COAuthToken_ImplicitGrantNoPrompt_Response::clear_access_token() {
  access_token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& COAuthToken_ImplicitGrantNoPrompt_Response::access_token() const {
  // @@protoc_insertion_point(field_get:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Response.access_token)
  return access_token_.GetNoArena();
}
inline void COAuthToken_ImplicitGrantNoPrompt_Response::set_access_token(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  access_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Response.access_token)
}
#if LANG_CXX11
inline void COAuthToken_ImplicitGrantNoPrompt_Response::set_access_token(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  access_token_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Response.access_token)
}
#endif
inline void COAuthToken_ImplicitGrantNoPrompt_Response::set_access_token(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  access_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Response.access_token)
}
inline void COAuthToken_ImplicitGrantNoPrompt_Response::set_access_token(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  access_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Response.access_token)
}
inline ::std::string* COAuthToken_ImplicitGrantNoPrompt_Response::mutable_access_token() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Response.access_token)
  return access_token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* COAuthToken_ImplicitGrantNoPrompt_Response::release_access_token() {
  // @@protoc_insertion_point(field_release:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Response.access_token)
  if (!has_access_token()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return access_token_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void COAuthToken_ImplicitGrantNoPrompt_Response::set_allocated_access_token(::std::string* access_token) {
  if (access_token != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  access_token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), access_token);
  // @@protoc_insertion_point(field_set_allocated:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Response.access_token)
}

// optional string redirect_uri = 2 [(.proto.dota.description) = "Redirection URI provided during client registration."];
inline bool COAuthToken_ImplicitGrantNoPrompt_Response::has_redirect_uri() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void COAuthToken_ImplicitGrantNoPrompt_Response::clear_redirect_uri() {
  redirect_uri_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& COAuthToken_ImplicitGrantNoPrompt_Response::redirect_uri() const {
  // @@protoc_insertion_point(field_get:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Response.redirect_uri)
  return redirect_uri_.GetNoArena();
}
inline void COAuthToken_ImplicitGrantNoPrompt_Response::set_redirect_uri(const ::std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  redirect_uri_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Response.redirect_uri)
}
#if LANG_CXX11
inline void COAuthToken_ImplicitGrantNoPrompt_Response::set_redirect_uri(::std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  redirect_uri_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Response.redirect_uri)
}
#endif
inline void COAuthToken_ImplicitGrantNoPrompt_Response::set_redirect_uri(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  redirect_uri_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Response.redirect_uri)
}
inline void COAuthToken_ImplicitGrantNoPrompt_Response::set_redirect_uri(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  redirect_uri_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Response.redirect_uri)
}
inline ::std::string* COAuthToken_ImplicitGrantNoPrompt_Response::mutable_redirect_uri() {
  _has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_mutable:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Response.redirect_uri)
  return redirect_uri_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* COAuthToken_ImplicitGrantNoPrompt_Response::release_redirect_uri() {
  // @@protoc_insertion_point(field_release:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Response.redirect_uri)
  if (!has_redirect_uri()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return redirect_uri_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void COAuthToken_ImplicitGrantNoPrompt_Response::set_allocated_redirect_uri(::std::string* redirect_uri) {
  if (redirect_uri != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  redirect_uri_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), redirect_uri);
  // @@protoc_insertion_point(field_set_allocated:proto.dota.COAuthToken_ImplicitGrantNoPrompt_Response.redirect_uri)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace dota
}  // namespace proto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_steammessages_5foauth_2esteamworkssdk_2eproto
